//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediKnock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Designation { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Picture { get; set; }
        public string VerificationCode { get; set; }
    }
}
