//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediKnock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public int ID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Sub_CategoryID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ProductName { get; set; }
        public string Heading { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Potency { get; set; }
        public string CompanyName { get; set; }
        public string ProductSell { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> CartID { get; set; }
        public Nullable<int> TotalPrice { get; set; }
    }
}
