//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediKnock.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeSlider
    {
        public int ID { get; set; }
        public string SliderImageName { get; set; }
        public string SliderImagePath { get; set; }
        public string SliderImageLink { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
